import { PersonModel } from "../Models/personModel";
import { AuthScope } from "../../Typings/Enums/authScope";
import AvatarAnastasia from "../../assets/avatar-anastasia.jpg";
import AvatarAndrew from "../../assets/avatar-andrew.jpg";
import AvatarMaria from "../../assets/avatar-maria.jpg";
import AvatarNataly from "../../assets/avatar-nataly.jpg";
import AvatarVictor from "../../assets/avatar-victor.jpg";
import AvatarRuslan from "../../assets/avatar-ruslan.jpg";
import AvatarIgor from "../../assets/avatar-igor.jpg";
import { MockDepartments } from "./mockDepartments";

// Used as demo mock db, can be updated during run by "post", "update" and "put requests"
export const MockPersons: Map<string, PersonModel> = new Map<string, PersonModel>([
    [
        "33bc751f-a56b-4704-bfb6-03239f04dcfc",
        {
            id: "33bc751f-a56b-4704-bfb6-03239f04dcfc",
            login: "regular",
            password: "123",
            fullName: "Крылова Анастасия Викторовна",
            authScope: AuthScope.regularUser,
            position: { name: "Junior Android разработчик" },
            isNewbie: false,
            email: "regular@mail.com",
            phoneNumber: "+78005553535",
            telegram: "stacy_tg",
            slack: "stacy",
            slackId: "UEM0NPR8Q",
            avatarUrl: AvatarAnastasia,
            department: MockDepartments[0],
        },
    ],
    [
        "3f3b75de-efcd-48aa-a59e-e805496467e1",
        {
            id: "3f3b75de-efcd-48aa-a59e-e805496467e1",
            login: "maria",
            password: "maria",
            fullName: "Гусева Мария Владимировна",
            authScope: AuthScope.regularUser,
            position: { name: "Middle Android разработчик" },
            isNewbie: false,
            email: "i.am.maria@mail.com",
            phoneNumber: "+78002343535",
            telegram: "mary-is-here",
            slack: "masha",
            slackId: "AEM2NPR8F",
            avatarUrl: AvatarMaria,
            department: MockDepartments[0],
        },
    ],
    [
        "ad59dd3c-bdec-4cc8-bb72-e460479a77e7",
        {
            id: "ad59dd3c-bdec-4cc8-bb72-e460479a77e7",
            login: "natalya",
            password: "natalya",
            fullName: "Шульц Наталья Викторовна",
            authScope: AuthScope.regularUser,
            position: { name: "Senior Android разработчик" },
            isNewbie: false,
            email: "shulz@mail.com",
            phoneNumber: "+78006783535",
            telegram: "shulz-senior",
            slack: "natali",
            slackId: "PEM2NPR8G",
            avatarUrl: AvatarNataly,
            department: MockDepartments[0],
        },
    ],
    [
        "b082dfe1-ab44-4547-9e31-0237e9e32eb4",
        {
            id: "b082dfe1-ab44-4547-9e31-0237e9e32eb4",
            login: "departmentManager",
            password: "12345",
            fullName: "Афанасьев Андрей Дмитриевич",
            authScope: AuthScope.departmentManager,
            position: { name: "Начальник отдела Android разработки" },
            isNewbie: false,
            email: "department.manager@mail.com",
            phoneNumber: "+78309903535",
            telegram: "andrew",
            slack: "andr",
            slackId: "VEM2NPR8R",
            avatarUrl: AvatarAndrew,
            department: MockDepartments[0],
        },
    ],
    [
        "0a3bba87-2322-493f-995c-f5f560d9f49b",
        {
            id: "0a3bba87-2322-493f-995c-f5f560d9f49b",
            login: "victor",
            password: "victor",
            fullName: "Лебедев Виктор Антонович",
            authScope: AuthScope.admin,
            position: { name: "Senior бекенд разработчик" },
            isNewbie: false,
            email: "victor@mail.com",
            phoneNumber: "+79235153535",
            telegram: "vitek",
            slack: "victor",
            slackId: "AEM2NPV8F",
            avatarUrl: AvatarVictor,
            department: MockDepartments[2],
        },
    ],
    [
        "419c3781-75ad-4792-9ad1-da30021bcbe7",
        {
            id: "419c3781-75ad-4792-9ad1-da30021bcbe7",
            login: "ruslan",
            password: "ruslan",
            fullName: "Купатов Руслан Дмитриевич",
            authScope: AuthScope.departmentManager,
            position: { name: "Начальник отдела бекенд разработки" },
            isNewbie: false,
            email: "rusik@mail.com",
            phoneNumber: "+79535553535",
            telegram: "rus_tut",
            slack: "ruslan",
            slackId: "CFM2NPV8B",
            avatarUrl: AvatarRuslan,
            department: MockDepartments[2],
        },
    ],
    [
        "1d5aee70-b83a-4f11-a744-993b8b3bfc26",
        {
            id: "1d5aee70-b83a-4f11-a744-993b8b3bfc26",
            login: "admin",
            password: "admin",
            fullName: "Чемозин Игорь Петрович",
            authScope: AuthScope.slackAdmin,
            position: { name: "Начальник отдела администрирования" },
            isNewbie: false,
            email: "admin@mail.com",
            phoneNumber: "+79535553535",
            telegram: "igoryanchik",
            slack: "igorr",
            slackId: "PFM2NPN8H",
            avatarUrl: AvatarIgor,
            department: MockDepartments[1],
        },
    ],
]);
