import { L10n, loadCldr } from "@syncfusion/ej2-base";
export function loadRussianCalendarLocale() {
    loadCldr(
        require("cldr-data/supplemental/numberingSystems.json"),
        require("cldr-data/main/ru/ca-gregorian.json"),
        require("cldr-data/main/ru/numbers.json"),
        require("cldr-data/main/ru/timeZoneNames.json")
    );

    //loadCldr(numberingSystems, gregorian, numbers, timeZoneNames);

    L10n.load({
        ru: {
            schedule: {
                day: "День",
                week: "Неделя",
                workWeek: "Рабочая неделя",
                month: "Месяц",
                year: "Год",
                agenda: "Agenda",
                weekAgenda: "Week Agenda",
                workWeekAgenda: "Work Week Agenda",
                monthAgenda: "Month Agenda",
                today: "Сегодня",
                noEvents: "Нет событий",
                emptyContainer: "В данный день нет событий",
                allDay: "Весь день",
                start: "Начало",
                end: "Конец",
                more: "еще",
                close: "Закрыть",
                cancel: "Отмена",
                noTitle: "(Нет заголовка)",
                delete: "Удалить",
                deleteEvent: "Удалить событие",
                deleteMultipleEvent: "Удалить несколько событий",
                selectedItems: "Выбрано элементов",
                deleteSeries: "Delete Series",
                edit: "Редактировать",
                editSeries: "Edit Series",
                editEvent: "Редактировать событие",
                createEvent: "Создать",
                subject: "Тема",
                addTitle: "Добавить заголовок",
                moreDetails: "Подробнее",
                save: "Сохранить",
                editContent: "Do you want to edit only this event or entire series?",
                deleteRecurrenceContent: "Do you want to delete only this event or entire series?",
                deleteContent: "Вы уверены, что хотите удалить это событие?",
                deleteMultipleContent: "Вы уверены, что хотите удалить выбранные события?",
                newEvent: "Новое событие",
                title: "Заголовок",
                location: "Location",
                description: "Description",
                timezone: "Timezone",
                startTimezone: "Start Timezone",
                endTimezone: "End Timezone",
                repeat: "Repeat",
                saveButton: "Сохранить",
                cancelButton: "Отмена",
                deleteButton: "Удалить",
                recurrence: "Recurrence",
                wrongPattern: "The recurrence pattern is not valid.",
                seriesChangeAlert:
                    "The changes made to specific instances of this series will be cancelled and those events will match the series again.",
                createError:
                    "The duration of the event must be shorter than how frequently it occurs. Shorten the duration, or change the recurrence pattern in the recurrence event editor.",
                recurrenceDateValidation:
                    "Some months have fewer than the selected date. For these months, the occurrence will fall on the last date of the month.",
                sameDayAlert: "Two occurrences of the same event cannot occur on the same day.",
                editRecurrence: "Edit Recurrence",
                repeats: "Repeats",
                alert: "Alert",
                startEndError: "The selected end date occurs before the start date.",
                invalidDateError: "The entered date value is invalid.",
                ok: "Ok",
                occurrence: "Occurrence",
                series: "Series",
                previous: "Previous",
                next: "Next",
                timelineDay: "Timeline Day",
                timelineWeek: "Timeline Week",
                timelineWorkWeek: "Timeline Work Week",
                timelineMonth: "Timeline Month",
                expandAllDaySection: "Expand",
                collapseAllDaySection: "Collapse",
            },
            recurrenceeditor: {
                none: "None",
                daily: "Daily",
                weekly: "Weekly",
                monthly: "Monthly",
                month: "Month",
                yearly: "Yearly",
                never: "Never",
                until: "Until",
                count: "Count",
                first: "First",
                second: "Second",
                third: "Third",
                fourth: "Fourth",
                last: "Last",
                repeat: "Repeat",
                repeatEvery: "Repeat Every",
                on: "Repeat On",
                end: "End",
                onDay: "Day",
                days: "Day(s)",
                weeks: "Week(s)",
                months: "Month(s)",
                years: "Year(s)",
                every: "every",
                summaryTimes: "time(s)",
                summaryOn: "on",
                summaryUntil: "until",
                summaryRepeat: "Repeats",
                summaryDay: "day(s)",
                summaryWeek: "week(s)",
                summaryMonth: "month(s)",
                summaryYear: "year(s)",
            },
        },
    });
}
